### ISSUE TITLE
Difference to reftex?

### ISSUE THREAD

**Issue by ouboub** [X9hRRDys/latex-labeler#1]
Hi

can you please tell me what is the difference betwenn your pkg and reftex?

thanks

Uwe Brauer

**Comment by X9hRRDys** [comment]
Hi.

Typing `C-c` `(` (the `reftex-label` command) in a math environment allows RefTeX to insert an equation label; however, the label number does not always match the equation number in the compiled PDF, even when using `M-x` `reftex-renumber-simple-labels`.

LaTeX Labeler is designed to create labels that are consistent with the numbers in the output PDF.

**Comment by ouboub** [comment]
>>> "X" == X9hRRDys  ***@***.***> writes:

> Hi.
> Typing `C-c (` (the `reftex-label` command) in a math environment
> allows RefTeX to insert an equation label; however, the label number
> does not always match the equation number in the compiled PDF, even
> when using `M-x` `reftex-renumber-simple-labels`.

> LaTeX Labeler is designed to create labels that are consistent with the numbers in the output PDF.

Just to get this straight. 

If I have 100 equations in my file and I decide to add a new equation at the beginning of the file, LaTeX labeler will run a **global** replace of all labels. Is this correct?

-- 
I strongly condemn Hamas heinous despicable pogroms/atrocities on Israel
I strongly condemn Putin's war of aggression against Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the EU and NATO membership of Ukraine.

**Comment by ouboub** [comment]
>>> "X" == X9hRRDys  ***@***.***> writes:

> Hi.
> Typing `C-c (` (the `reftex-label` command) in a math environment
> allows RefTeX to insert an equation label; however, the label number
> does not always match the equation number in the compiled PDF, even
> when using `M-x` `reftex-renumber-simple-labels`.

> LaTeX Labeler is designed to create labels that are consistent with the numbers in the output PDF.

Just to get this straight. 

If I have 100 equations in my file and I decide to add a new equation at the beginning of the file, LaTeX labeler will run a **global** replace of all labels. Is this correct?

-- 
I strongly condemn Hamas heinous despicable pogroms/atrocities on Israel
I strongly condemn Putin's war of aggression against Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the EU and NATO membership of Ukraine.

**Comment by X9hRRDys** [comment]
Yes, that is correct.

**Comment by ouboub** [comment]
>>> "X" == X9hRRDys  ***@***.***> writes:

> Yes, that is correct.


And all the corresponding references I presume?

There is a disadvantage with your method.

I use a file prefix for my reftex labels like
```
    \label{eq:continuation-criterion:5}
```
from the file continue-criterion.tex 

That allows me in a different file (and not using include or subfiles) to use
```
\usepackage{xr-hyper}
\usepackage[colorlinks]{hyperref}
\externaldocument[D-]{continuation-criterion}
```
And then cite \label{eq:continuation-criterion:5}
for example as \eqref{D-eq:continuation-criterion:5}

That would not work with your package I understand

**Comment by ouboub** [comment]
>> "X" == X9hRRDys  ***@***.***> writes:
 Yes, that is correct.
And all the corresponding references I presume?

There is a disadvantage with your method.

I use a file prefix for my reftex labels like
```
    \label{eq:continuation-criterion:5}
```
from the file continue-criterion.tex

That allows me in a different file (and not using include or subfiles) to use
``` latex
\usepackage{xr-hyper}
\usepackage[colorlinks]{hyperref}
\externaldocument[D-]{continuation-criterion}
```
And then cite \label{eq:continuation-criterion:5}
for example as \eqref{D-eq:continuation-criterion:5}

That would not work with your package I understand

**Comment by X9hRRDys** [comment]
You are right.

LaTeX Labeler replaces labels and references only within the file being edited, even if the file is referenced in other files.

In the README, there is a section titled "Note for multi-file documents," which explains how to use it when the file is referenced by other files, but I understand that this is not a fundamental solution.

If equations are frequently referenced in other files, I generally do not recommend using LaTeX Labeler.
